customhost = "employee.chcn6qzdv5sy.ap-southeast-2.rds.amazonaws.com"
customuser = "Harshithapriya"
custompass = "Pinkvenom"
customdb = "employee"
custombucket = "employeeone"
customregion = "ap-southease-2"
